### ISSUE TITLE
Library direction

### ISSUE THREAD

**Issue by ghost** [OnyoCoder/inkster-py#4]
Was directed by yourself to make an issue to answer a query that I asked in a Discord server:

> [15:24] nekoka: what case would you use a third party library to add two numbers instead of the + operator or operator.add which is part of every version of Python without installing anything from PyPI?
> [15:24] Onyo: Make a issue

Is any clarification available?

Thanks

**Comment by AbxyPlayz** [comment]
I don't think its useless but its not always gonna be removed but it could be a extension to the discord bots unless you want some math then just use the lib you made the bot in because it already has a math extension lol(I will comment again in a few secs)

**Comment by tandemdude** [comment]
I agree with nekoka
These maths functions have no use and are just bloat in this project. Everything you provide is already provided by the standard library

**Comment by OnyoCoder** [comment]
Uhhh so AbxyPlayz is a little right since it could be a little helping in the discord bots but I wont lie it is a little useless but I'm gonna wait until AbxyPlayz comments again to respond with a better comment

**Comment by ahnaf-zamil** [comment]
Honestly, I agree with Nekoka, we don't need a math lib since the standard library of Python already has them. So why not waste time on that but work on the Discord API wrapper instead?

**Comment by AbxyPlayz** [comment]
I guess we can remove educational.py but what about the other knowledge stuff we was gonna do with wolfram api? Besides the math

**Comment by tandemdude** [comment]
Sounds like you actually have no idea of the main purpose of the project. Usually you do one thing and focus on that, not 50 different things, most of which will never be used

**Comment by OnyoCoder** [comment]
I'm gonna uh I guess we can remove educational.py but if I want to add it back I will. I hope I have helped you with your issue this issue is now being closed. Have a nice day!
